INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0001,'Computador HP','',);
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0002,'Televisor Samsung','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0003,'Silla roja','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0004,'Maquillaje L'oreal','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0005,'Microondas Kalley','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0006,'Diademas Sony','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0007,'Conjunto Adidas','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0008,'Zapatos negros puma','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0009,'Bicicleta Electrica','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0010,'Sofa Cama','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0011,'Reloj Rolex','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0012,'Cama acolchonada','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0013,'','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0014,'','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0015,'','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0016,'','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0017,'','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0018,'','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0019,'','','','');
INSERT INTO Productos(producto_id,nombre,categoria,sku,precio,stock) VALUES (0020,'','','','');
